// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::OptionalHeaderFields", generatedBy by: "WriteSeqStructDcl"
type CosNotificationOptionalHeaderFields struct {
	__goidl__.IdlObject
	Array []CosNotificationProperty `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationOptionalHeaderFieldsId_Const = "IDL:CosNotification/OptionalHeaderFields:1.0"

func (self *CosNotificationOptionalHeaderFields) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationOptionalHeaderFields) GoString() string {
	return self.String()
}

func (self *CosNotificationOptionalHeaderFields) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationOptionalHeaderFields_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationOptionalHeaderFieldsHelper = CosNotificationOptionalHeaderFields_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationOptionalHeaderFieldsId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.OptionalHeaderFields.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationOptionalHeaderFields{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationOptionalHeaderFields{}
			},
			__reflect__.TypeOf((*CosNotificationOptionalHeaderFields)(nil))))
}
