// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::EventTypeSeq", generatedBy by: "WriteSeqStructDcl"
type CosNotificationEventTypeSeq struct {
	__goidl__.IdlObject
	Array []CosNotificationEventType `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventTypeSeqId_Const = "IDL:CosNotification/EventTypeSeq:1.0"

func (self *CosNotificationEventTypeSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationEventTypeSeq) GoString() string {
	return self.String()
}

func (self *CosNotificationEventTypeSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationEventTypeSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationEventTypeSeqHelper = CosNotificationEventTypeSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationEventTypeSeqId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.EventTypeSeq.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationEventTypeSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationEventTypeSeq{}
			},
			__reflect__.TypeOf((*CosNotificationEventTypeSeq)(nil))))
}
