// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::FilterableEventBody", generatedBy by: "WriteSeqStructDcl"
type CosNotificationFilterableEventBody struct {
	__goidl__.IdlObject
	Array []CosNotificationProperty `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationFilterableEventBodyId_Const = "IDL:CosNotification/FilterableEventBody:1.0"

func (self *CosNotificationFilterableEventBody) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationFilterableEventBody) GoString() string {
	return self.String()
}

func (self *CosNotificationFilterableEventBody) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationFilterableEventBody_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationFilterableEventBodyHelper = CosNotificationFilterableEventBody_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationFilterableEventBodyId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.FilterableEventBody.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationFilterableEventBody{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationFilterableEventBody{}
			},
			__reflect__.TypeOf((*CosNotificationFilterableEventBody)(nil))))
}
