// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Exception declaration: "CosNotification::UnsupportedQoS", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosNotificationUnsupportedQoS struct {
	__goidl__.IdlObject
	QosErr CosNotificationPropertyErrorSeq `json:"QosErr"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationUnsupportedQoSId_Const = "IDL:omg.org/CosNotification/UnsupportedQoS:1.0"

func (self *CosNotificationUnsupportedQoS) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationUnsupportedQoS) Error() string{
	return 	__fmt__.Sprintf("Error of type CosNotificationUnsupportedQoS(%v)", self.String())
}
func (self *CosNotificationUnsupportedQoS) GoString() string {
	return self.String()
}

func (self *CosNotificationUnsupportedQoS) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.QosErr.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedQoS) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedQoS) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.QosErr.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationUnsupportedQoS_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationUnsupportedQoSHelper = CosNotificationUnsupportedQoS_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationUnsupportedQoSId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.UnsupportedQoS.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationUnsupportedQoS{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationUnsupportedQoS{}
			},
			__reflect__.TypeOf((*CosNotificationUnsupportedQoS)(nil))))
}
