// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::EventBatch", generatedBy by: "WriteSeqStructDcl"
type CosNotificationEventBatch struct {
	__goidl__.IdlObject
	Array []CosNotificationStructuredEvent `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventBatchId_Const = "IDL:CosNotification/EventBatch:1.0"

func (self *CosNotificationEventBatch) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationEventBatch) GoString() string {
	return self.String()
}

func (self *CosNotificationEventBatch) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationEventBatch_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationEventBatchHelper = CosNotificationEventBatch_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationEventBatchId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.EventBatch.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationEventBatch{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationEventBatch{}
			},
			__reflect__.TypeOf((*CosNotificationEventBatch)(nil))))
}
