// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::AdminProperties", generatedBy by: "WriteSeqStructDcl"
type CosNotificationAdminProperties struct {
	__goidl__.IdlObject
	Array []CosNotificationProperty `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationAdminPropertiesId_Const = "IDL:CosNotification/AdminProperties:1.0"

func (self *CosNotificationAdminProperties) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationAdminProperties) GoString() string {
	return self.String()
}

func (self *CosNotificationAdminProperties) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationAdminProperties_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationAdminPropertiesHelper = CosNotificationAdminProperties_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationAdminPropertiesId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.AdminProperties.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationAdminProperties{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationAdminProperties{}
			},
			__reflect__.TypeOf((*CosNotificationAdminProperties)(nil))))
}
