// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::QoSProperties", generatedBy by: "WriteSeqStructDcl"
type CosNotificationQoSProperties struct {
	__goidl__.IdlObject
	Array []CosNotificationProperty `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSPropertiesId_Const = "IDL:CosNotification/QoSProperties:1.0"

func (self *CosNotificationQoSProperties) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSProperties) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSProperties) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSProperties_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSPropertiesHelper = CosNotificationQoSProperties_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSPropertiesId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.QoSProperties.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSProperties{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSProperties{}
			},
			__reflect__.TypeOf((*CosNotificationQoSProperties)(nil))))
}
