// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CosNotification::QoSAdmin", generatedBy by: "WriteInterface"
type CosNotificationQoSAdmin interface {
	// Interface operations
	// Original name: "get_qos"
	GetQos() (result *CosNotificationQoSProperties, err error)
	//Exceptions for : SetQos
	//	CosNotificationUnsupportedQoS
	// Original name: "set_qos"
	SetQos(Qos *CosNotificationQoSProperties) (error error)
	//Exceptions for : ValidateQos
	//	CosNotificationUnsupportedQoS
	// Original name: "validate_qos"
	ValidateQos(RequiredQos *CosNotificationQoSProperties) (AvailableQos *CosNotificationNamedPropertyRangeSeq, error error)
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdmin_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminId_Const = "IDL:omg.org/CosNotification/QoSAdmin:1.0"

func (self CosNotificationQoSAdmin_Helper) Id() string {
	return CosNotificationQoSAdminId_Const
}

func (self CosNotificationQoSAdmin_Helper) Read(stream __goidl__.IReadAny) (CosNotificationQoSAdmin, error) {
	return nil, nil
}

func (self CosNotificationQoSAdmin_Helper) Write(stream __goidl__.IWriteAny, v CosNotificationQoSAdmin) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminHelper = CosNotificationQoSAdmin_Helper{}

func init() {
}
