// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "CosNotification::Istring", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::Istring" from: "string"
type CosNotificationIstring string

//noinspection GoSnakeCaseUsage
type CosNotificationIstring_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationIstringId_Const = "IDL:omg.org/CosNotification/Istring:1.0"

func (self CosNotificationIstring_Helper) Id() string {
	return CosNotificationIstringId_Const
}

func (self CosNotificationIstring_Helper) Read(stream __goidl__.IReadAny) (string, error) {
	result, err := __goidl__.IdlStringHelper.Read(stream)
	return result, err
}

func (self CosNotificationIstring_Helper) Write(stream __goidl__.IWriteAny, v string) error {
	return __goidl__.IdlStringHelper.Write(stream, v)
}

// TypeDef declaration: "CosNotification::PropertyName", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::PropertyName" from: "string"
type CosNotificationPropertyName string

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyName_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyNameId_Const = "IDL:omg.org/CosNotification/PropertyName:1.0"

func (self CosNotificationPropertyName_Helper) Id() string {
	return CosNotificationPropertyNameId_Const
}

func (self CosNotificationPropertyName_Helper) Read(stream __goidl__.IReadAny) (string, error) {
	result, err := __goidl__.IdlStringHelper.Read(stream)
	return result, err
}

func (self CosNotificationPropertyName_Helper) Write(stream __goidl__.IWriteAny, v string) error {
	return __goidl__.IdlStringHelper.Write(stream, v)
}

// TypeDef declaration: "CosNotification::PropertyValue", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CosNotification::PropertyValue" from: "__goidl__.IdlAny"
type CosNotificationPropertyValue __goidl__.IdlAny

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyValue_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyValueId_Const = "IDL:omg.org/CosNotification/PropertyValue:1.0"

func (self CosNotificationPropertyValue_Helper) Id() string {
	return CosNotificationPropertyValueId_Const
}

func (self CosNotificationPropertyValue_Helper) Read(stream __goidl__.IReadAny) (__goidl__.IdlAny, error) {
	result, err := __goidl__.IdlAnyHelper.Read(stream)
	return result, err
}

func (self CosNotificationPropertyValue_Helper) Write(stream __goidl__.IWriteAny, v __goidl__.IdlAny) error {
	return __goidl__.IdlAnyHelper.Write(stream, v)
}

// Constant declaration: "CosNotification::EventReliability", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationEventReliability string = "EventReliability"

// Constant declaration: "CosNotification::BestEffort", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationBestEffort int16 = 0

// Constant declaration: "CosNotification::Persistent", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPersistent int16 = 1

// Constant declaration: "CosNotification::ConnectionReliability", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationConnectionReliability string = "ConnectionReliability"

// Constant declaration: "CosNotification::Priority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPriority string = "Priority"

// Constant declaration: "CosNotification::LowestPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationLowestPriority int16 = -32767

// Constant declaration: "CosNotification::HighestPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationHighestPriority int16 = 32767

// Constant declaration: "CosNotification::DefaultPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDefaultPriority int16 = 0

// Constant declaration: "CosNotification::StartTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStartTime string = "StartTime"

// Constant declaration: "CosNotification::StopTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStopTime string = "StopTime"

// Constant declaration: "CosNotification::Timeout", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationTimeout string = "Timeout"

// Constant declaration: "CosNotification::OrderPolicy", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationOrderPolicy string = "OrderPolicy"

// Constant declaration: "CosNotification::AnyOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationAnyOrder int16 = 0

// Constant declaration: "CosNotification::FifoOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationFifoOrder int16 = 1

// Constant declaration: "CosNotification::PriorityOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPriorityOrder int16 = 2

// Constant declaration: "CosNotification::DeadlineOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDeadlineOrder int16 = 3

// Constant declaration: "CosNotification::DiscardPolicy", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationDiscardPolicy string = "DiscardPolicy"

// Constant declaration: "CosNotification::LifoOrder", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationLifoOrder int16 = 4

// Constant declaration: "CosNotification::MaximumBatchSize", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaximumBatchSize string = "MaximumBatchSize"

// Constant declaration: "CosNotification::PacingInterval", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationPacingInterval string = "PacingInterval"

// Constant declaration: "CosNotification::StartTimeSupported", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStartTimeSupported string = "StartTimeSupported"

// Constant declaration: "CosNotification::StopTimeSupported", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationStopTimeSupported string = "StopTimeSupported"

// Constant declaration: "CosNotification::MaxEventsPerConsumer", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxEventsPerConsumer string = "MaxEventsPerConsumer"

// Constant declaration: "CosNotification::MaxQueueLength", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxQueueLength string = "MaxQueueLength"

// Constant declaration: "CosNotification::MaxConsumers", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxConsumers string = "MaxConsumers"

// Constant declaration: "CosNotification::MaxSuppliers", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationMaxSuppliers string = "MaxSuppliers"

// Constant declaration: "CosNotification::RejectNewEvents", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CosNotificationRejectNewEvents string = "RejectNewEvents"


//noinspection GoUnusedGlobalVariable
var CosNotificationIstringHelper = CosNotificationIstring_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyNameHelper = CosNotificationPropertyName_Helper{}

//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyValueHelper = CosNotificationPropertyValue_Helper{}

func init() {
}
