// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::PropertyErrorSeq", generatedBy by: "WriteSeqStructDcl"
type CosNotificationPropertyErrorSeq struct {
	__goidl__.IdlObject
	Array []CosNotificationPropertyError `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyErrorSeqId_Const = "IDL:CosNotification/PropertyErrorSeq:1.0"

func (self *CosNotificationPropertyErrorSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationPropertyErrorSeq) GoString() string {
	return self.String()
}

func (self *CosNotificationPropertyErrorSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyErrorSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyErrorSeqHelper = CosNotificationPropertyErrorSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationPropertyErrorSeqId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.PropertyErrorSeq.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationPropertyErrorSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationPropertyErrorSeq{}
			},
			__reflect__.TypeOf((*CosNotificationPropertyErrorSeq)(nil))))
}
