// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::PropertyRange", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationPropertyRange struct {
	__goidl__.IdlObject
	LowVal __goidl__.IdlAny `json:"LowVal"`
	HighVal __goidl__.IdlAny `json:"HighVal"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationPropertyRangeId_Const = "IDL:omg.org/CosNotification/PropertyRange:1.0"

func (self *CosNotificationPropertyRange) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationPropertyRange) GoString() string {
	return self.String()
}

func (self *CosNotificationPropertyRange) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.LowVal, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.HighVal, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyRange) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationPropertyRange) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.LowVal)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.HighVal)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationPropertyRange_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationPropertyRangeHelper = CosNotificationPropertyRange_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationPropertyRangeId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.PropertyRange.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationPropertyRange{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationPropertyRange{}
			},
			__reflect__.TypeOf((*CosNotificationPropertyRange)(nil))))
}
