// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Struct declaration: "CosNotification::NamedPropertyRangeSeq", generatedBy by: "WriteSeqStructDcl"
type CosNotificationNamedPropertyRangeSeq struct {
	__goidl__.IdlObject
	Array []CosNotificationNamedPropertyRange `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationNamedPropertyRangeSeqId_Const = "IDL:CosNotification/NamedPropertyRangeSeq:1.0"

func (self *CosNotificationNamedPropertyRangeSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationNamedPropertyRangeSeq) GoString() string {
	return self.String()
}

func (self *CosNotificationNamedPropertyRangeSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationNamedPropertyRangeSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationNamedPropertyRangeSeqHelper = CosNotificationNamedPropertyRangeSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationNamedPropertyRangeSeqId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.NamedPropertyRangeSeq.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationNamedPropertyRangeSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationNamedPropertyRangeSeq{}
			},
			__reflect__.TypeOf((*CosNotificationNamedPropertyRangeSeq)(nil))))
}
