// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Exception declaration: "CosNotification::UnsupportedAdmin", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CosNotificationUnsupportedAdmin struct {
	__goidl__.IdlObject
	AdminErr CosNotificationPropertyErrorSeq `json:"AdminErr"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationUnsupportedAdminId_Const = "IDL:omg.org/CosNotification/UnsupportedAdmin:1.0"

func (self *CosNotificationUnsupportedAdmin) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationUnsupportedAdmin) Error() string{
	return 	__fmt__.Sprintf("Error of type CosNotificationUnsupportedAdmin(%v)", self.String())
}
func (self *CosNotificationUnsupportedAdmin) GoString() string {
	return self.String()
}

func (self *CosNotificationUnsupportedAdmin) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.AdminErr.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedAdmin) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationUnsupportedAdmin) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.AdminErr.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationUnsupportedAdmin_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationUnsupportedAdminHelper = CosNotificationUnsupportedAdmin_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationUnsupportedAdminId_Const,
			__yaccidl__.IdlStruct,
			"CosNotification.idl.UnsupportedAdmin.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationUnsupportedAdmin{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationUnsupportedAdmin{}
			},
			__reflect__.TypeOf((*CosNotificationUnsupportedAdmin)(nil))))
}
