// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::QoSAdmin_set_qos_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationQoSAdminSetQosIn struct {
	__goidl__.IdlObject
	Qos CosNotificationQoSProperties `json:"Qos"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminSetQosInId_Const = "IDL:CosNotification/QoSAdmin_set_qos_In:1.0"

func (self *CosNotificationQoSAdminSetQosIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSAdminSetQosIn) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSAdminSetQosIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Qos.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminSetQosIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminSetQosIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Qos.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdminSetQosIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminSetQosInHelper = CosNotificationQoSAdminSetQosIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSAdminSetQosInId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationQoSAdminSetQosIn.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSAdminSetQosIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSAdminSetQosIn{}
			},
			__reflect__.TypeOf((*CosNotificationQoSAdminSetQosIn)(nil))))
}
