// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

// Struct declaration: "CosNotification::QoSAdmin_Stub", generatedBy by: "WriteStructDcl"
type CosNotificationQoSAdminStub struct {
}


func init() {
}
