// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::AdminPropertiesAdmin_set_admin_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationAdminPropertiesAdminSetAdminOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosNotificationAdminPropertiesAdminSetAdminOutId_Const = "IDL:CosNotification/AdminPropertiesAdmin_set_admin_Out:1.0"

func (self *CosNotificationAdminPropertiesAdminSetAdminOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationAdminPropertiesAdminSetAdminOut) GoString() string {
	return self.String()
}

func (self *CosNotificationAdminPropertiesAdminSetAdminOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationAdminPropertiesAdminSetAdminOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationAdminPropertiesAdminSetAdminOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationAdminPropertiesAdminSetAdminOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationAdminPropertiesAdminSetAdminOutHelper = CosNotificationAdminPropertiesAdminSetAdminOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationAdminPropertiesAdminSetAdminOutId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationAdminPropertiesAdminSetAdminOut.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationAdminPropertiesAdminSetAdminOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationAdminPropertiesAdminSetAdminOut{}
			},
			__reflect__.TypeOf((*CosNotificationAdminPropertiesAdminSetAdminOut)(nil))))
}
