// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::QoSAdmin_validate_qos_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationQoSAdminValidateQosOut struct {
	__goidl__.IdlObject
	AvailableQos CosNotificationNamedPropertyRangeSeq `json:"AvailableQos"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminValidateQosOutId_Const = "IDL:CosNotification/QoSAdmin_validate_qos_Out:1.0"

func (self *CosNotificationQoSAdminValidateQosOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSAdminValidateQosOut) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSAdminValidateQosOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.AvailableQos.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminValidateQosOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminValidateQosOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.AvailableQos.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdminValidateQosOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminValidateQosOutHelper = CosNotificationQoSAdminValidateQosOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSAdminValidateQosOutId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationQoSAdminValidateQosOut.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSAdminValidateQosOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSAdminValidateQosOut{}
			},
			__reflect__.TypeOf((*CosNotificationQoSAdminValidateQosOut)(nil))))
}
