// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::QoSAdmin_get_qos_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationQoSAdminGetQosIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminGetQosInId_Const = "IDL:CosNotification/QoSAdmin_get_qos_In:1.0"

func (self *CosNotificationQoSAdminGetQosIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSAdminGetQosIn) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSAdminGetQosIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminGetQosIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminGetQosIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdminGetQosIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminGetQosInHelper = CosNotificationQoSAdminGetQosIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSAdminGetQosInId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationQoSAdminGetQosIn.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSAdminGetQosIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSAdminGetQosIn{}
			},
			__reflect__.TypeOf((*CosNotificationQoSAdminGetQosIn)(nil))))
}
