// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::EventBatch", generatedBy by: "WriteStructSequenceDcl"
type CosNotificationEventBatch struct {
	__goidl__.IdlObject
	Array []*CosNotificationStructuredEvent `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CosNotificationEventBatchId_Const = "IDL:CosNotification/EventBatch:1.0"

func (self *CosNotificationEventBatch) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationEventBatch) GoString() string {
	return self.String()
}

func (self *CosNotificationEventBatch) ReadValue(stream __goidl__.IReadAny) error {
	err := self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	var n uint32
	n, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	if n > 0 {
		self.Array = make([]*CosNotificationStructuredEvent, n)
		var i uint32
		for i = 0; i < n; i++ {
			self.Array[i] = &CosNotificationStructuredEvent{}
			err = self.Array[i].ReadValue(stream)
				if err != nil {
				return err
			}
		}
	}
	return nil
}

func (self *CosNotificationEventBatch) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationEventBatch) Write(stream __goidl__.IWriteAny) error {
	err := self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	err = __goidl__.IdlUInt32Helper.Write(stream, uint32(len(self.Array)))
	if err != nil {
	return err
	}
	if len(self.Array) > 0 {
		for _, item := range self.Array {
			err = item.Write(stream)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationEventBatch_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationEventBatchHelper = CosNotificationEventBatch_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationEventBatchId_Const,
			__goidl__.SequenceType,
			"CosNotification.idl",
			"xdl_CosNotificationEventBatch.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationEventBatch{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationEventBatch{}
			},
			__reflect__.TypeOf((*CosNotificationEventBatch)(nil))))
}
