// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

// Struct declaration: "CosNotification::AdminPropertiesAdmin_Stub", generatedBy by: "WriteStructDcl"
type CosNotificationAdminPropertiesAdminStub struct {
}


func init() {
}
