// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::QoSAdmin_set_qos_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationQoSAdminSetQosOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminSetQosOutId_Const = "IDL:CosNotification/QoSAdmin_set_qos_Out:1.0"

func (self *CosNotificationQoSAdminSetQosOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSAdminSetQosOut) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSAdminSetQosOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminSetQosOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminSetQosOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdminSetQosOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminSetQosOutHelper = CosNotificationQoSAdminSetQosOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSAdminSetQosOutId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationQoSAdminSetQosOut.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSAdminSetQosOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSAdminSetQosOut{}
			},
			__reflect__.TypeOf((*CosNotificationQoSAdminSetQosOut)(nil))))
}
