// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::QoSAdmin_get_qos_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationQoSAdminGetQosOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosNotificationQoSAdminGetQosOutId_Const = "IDL:CosNotification/QoSAdmin_get_qos_Out:1.0"

func (self *CosNotificationQoSAdminGetQosOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationQoSAdminGetQosOut) GoString() string {
	return self.String()
}

func (self *CosNotificationQoSAdminGetQosOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminGetQosOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationQoSAdminGetQosOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationQoSAdminGetQosOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationQoSAdminGetQosOutHelper = CosNotificationQoSAdminGetQosOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationQoSAdminGetQosOutId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationQoSAdminGetQosOut.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationQoSAdminGetQosOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationQoSAdminGetQosOut{}
			},
			__reflect__.TypeOf((*CosNotificationQoSAdminGetQosOut)(nil))))
}
