// Code generated by me. DO NOT EDIT.

package goIdlCosNotification

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CosNotification::AdminPropertiesAdmin_get_admin_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CosNotificationAdminPropertiesAdminGetAdminIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CosNotificationAdminPropertiesAdminGetAdminInId_Const = "IDL:CosNotification/AdminPropertiesAdmin_get_admin_In:1.0"

func (self *CosNotificationAdminPropertiesAdminGetAdminIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CosNotificationAdminPropertiesAdminGetAdminIn) GoString() string {
	return self.String()
}

func (self *CosNotificationAdminPropertiesAdminGetAdminIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationAdminPropertiesAdminGetAdminIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CosNotificationAdminPropertiesAdminGetAdminIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CosNotificationAdminPropertiesAdminGetAdminIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CosNotificationAdminPropertiesAdminGetAdminInHelper = CosNotificationAdminPropertiesAdminGetAdminIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CosNotificationAdminPropertiesAdminGetAdminInId_Const,
			__goidl__.StructType,
			"CosNotification.idl",
			"xdl_CosNotificationAdminPropertiesAdminGetAdminIn.go",
			func() __goidl__.IIdlObject {
				return &CosNotificationAdminPropertiesAdminGetAdminIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CosNotificationAdminPropertiesAdminGetAdminIn{}
			},
			__reflect__.TypeOf((*CosNotificationAdminPropertiesAdminGetAdminIn)(nil))))
}
